export function generateStoreData() {
  return {
    store: {
      name: "AutoPilot Store - Bandra West",
      location: "Mumbai, Maharashtra",
      hours: "6:00 AM - 11:00 PM",
      status: "open",
      todayRevenue: 45600,
      manager: "Priya Sharma",
    },
    metrics: {
      totalOrders: 127,
      orderGrowth: 15,
      activeCustomers: 23,
      ecoScore: 8.5,
    },
    alerts: [
      {
        id: "1",
        type: "stock",
        message: "Tata Salt running low - only 15 units left",
        priority: "high" as const,
        product: "Tata Salt 1kg",
      },
      {
        id: "2",
        type: "stock",
        message: "Amul Milk about to expire - 25 units",
        priority: "high" as const,
        product: "Amul Fresh Milk",
      },
      {
        id: "3",
        type: "demand",
        message: "High demand expected for Umbrella due to rain forecast",
        priority: "medium" as const,
        product: "Compact Umbrella",
      },
    ],
    inventory: [
      {
        id: "1",
        name: "Tata Salt 1kg",
        category: "Groceries",
        currentStock: 15,
        minStock: 50,
        maxStock: 200,
        price: 22,
        lastRestocked: "2 days ago",
        supplier: "Tata Consumer",
        status: "critical" as const,
      },
      {
        id: "2",
        name: "Amul Fresh Milk 1L",
        category: "Dairy",
        currentStock: 45,
        minStock: 30,
        maxStock: 100,
        price: 56,
        lastRestocked: "Today",
        supplier: "Amul Dairy",
        status: "healthy" as const,
      },
      {
        id: "3",
        name: "Maggi Noodles 2-min",
        category: "Instant Food",
        currentStock: 25,
        minStock: 40,
        maxStock: 150,
        price: 14,
        lastRestocked: "3 days ago",
        supplier: "Nestle India",
        status: "low" as const,
      },
      {
        id: "4",
        name: "Cotton Kurta Set",
        category: "Clothing",
        currentStock: 8,
        minStock: 5,
        maxStock: 25,
        price: 899,
        lastRestocked: "1 week ago",
        supplier: "FabIndia",
        status: "healthy" as const,
      },
      {
        id: "5",
        name: "Compact Umbrella",
        category: "Accessories",
        currentStock: 12,
        minStock: 10,
        maxStock: 30,
        price: 299,
        lastRestocked: "5 days ago",
        supplier: "Local Supplier",
        status: "healthy" as const,
      },
      {
        id: "6",
        name: "Parle-G Biscuits",
        category: "Snacks",
        currentStock: 85,
        minStock: 30,
        maxStock: 80,
        price: 10,
        lastRestocked: "Yesterday",
        supplier: "Parle Products",
        status: "overstock" as const,
      },
    ],
    recentOrders: [
      {
        id: "ORD001",
        customer: "Rahul Mehta",
        amount: 450,
        status: "completed",
        time: "10 mins ago",
      },
      {
        id: "ORD002",
        customer: "Kavya Iyer",
        amount: 1200,
        status: "preparing",
        time: "15 mins ago",
      },
      {
        id: "ORD003",
        customer: "Arjun Nair",
        amount: 680,
        status: "ready",
        time: "25 mins ago",
      },
    ],
    deliveries: [
      {
        orderId: "ORD001",
        progress: 85,
        status: "out for delivery",
        eta: "10 mins",
        area: "Bandra East",
      },
      {
        orderId: "ORD004",
        progress: 45,
        status: "in transit",
        eta: "25 mins",
        area: "Khar West",
      },
    ],
    demandData: [
      { hour: "6 AM", demand: 45, prediction: 50 },
      { hour: "9 AM", demand: 120, prediction: 115 },
      { hour: "12 PM", demand: 200, prediction: 195 },
      { hour: "3 PM", demand: 150, prediction: 160 },
      { hour: "6 PM", demand: 280, prediction: 275 },
      { hour: "9 PM", demand: 180, prediction: 185 },
    ],
    localTrends: [
      {
        product: "Raincoat",
        trend: "+45%",
        reason: "Heavy rain expected in Mumbai",
        icon: "🌧️",
      },
      {
        product: "Hot Beverages",
        trend: "+23%",
        reason: "Monsoon season demand",
        icon: "☕",
      },
      {
        product: "Fresh Vegetables",
        trend: "+18%",
        reason: "Weekend cooking trend",
        icon: "🥬",
      },
    ],
    performance: {
      salesGrowth: 15.6,
      customerSatisfaction: 4.7,
      inventoryTurnover: 8.2,
      ecoScore: 8.5,
    },
  }
}
